name: homeroute_store
description: HomeRoute Store - Android app store client
publish_to: 'none'
version: 2.1.8+8

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  go_router: ^14.0.0
  flutter_secure_storage: ^9.2.0
  shared_preferences: ^2.3.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/adaptive-icon.png
